language: node_js
node_js:
  - "12.1.0"

cache:
  directories:
    - node_modules

script: npm run test

before_deploy:
  - sudo apt-get install -y ttf-mscorefonts-installer
  - npm run build

deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: master
