#!/bin/bash

# post-receive git hook to deploy via jekyll
#
# assumes run in bare repo addressable by $GIT_DIR

echo "Executing post-receive hook"

SRC='ln'
TMP=`mktemp -d`
OUT='/home/public'

echo "Building $SRC from $GIT_DIR to $OUT"

git clone $GIT_DIR $TMP

jekyll build -s $TMP/$SRC -d $OUT

# gzip html
find $OUT/ \( -iname '*.html' -o -iname '*.js' -o -iname '*.css' \) -exec bash -c 'gzip -n -c --best "{}" > "{}".gz' \;
