#!/bin/sh

# post-update git hook to be run from bare repo on server
#
# requires this repo is set up as a remote named src in the $PUB repo, e.g.
#
#  src    /home/private/devm33.git
#

echo "-------------------------------------------------------------------------"
echo "Executing post-update hook"

PUB='/home/public'

cd $PUB || exit
unset GIT_DIR
git pull src master

exec git update-server-info
