#!/bin/sh

# post-receive git hook to deploy via jekyll
#
# assumes run in bare repo addressable by $GIT_DIR

echo "Executing post-receive hook"

SRC='ln'
TMP='/tmp/devm33'
OUT='/home/public'

echo "Building $SRC from $GIT_DIR to $OUT"

rm -rf $TMP

rm -rf $OUT/*

git clone $GIT_DIR $TMP

jekyll build -s $TMP/$SRC -d $OUT

rm -rf $TMP
