name: CI
on:
  push:
    # Only trigger on commit pushes, not tags
    branches:
      - "**"
    tags-ignore:
      - "**"
permissions:
  contents: write
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          # Checkout and push to the branch that triggered the workflow
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - name: Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
      - run: npm ci
      - run: PUPPETEER_EXECUTABLE_PATH=$(which chromium-browser) npm run build
      - run: npm test
      - run: npm run format
      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git diff --quiet && git diff --staged --quiet || (git commit -am "Automated formatting" && git push)
